services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: tukanoUser
      POSTGRES_PASSWORD: tukanoPassword
      POSTGRES_DB: tukanoDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-container
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - java_app_data:/app/data
    environment:
      REDIS_HOSTNAME: redis-cache
      REDIS_PORT: 6379
volumes:
  postgres_data:
  java_app_data:
  redis_data: