services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: tukanoUser
      POSTGRES_PASSWORD: tukanoPassword
      POSTGRES_DB: tukanoDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-container
    depends_on:
      - postgres
      - redis
      - blob-service
    ports:
      - "8080:8080"
    environment:
      REDIS_HOSTNAME: redis-cache
      REDIS_PORT: 6379
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: tukanoDatabase
      POSTGRES_USER: tukanoUser
      POSTGRES_PASSWORD: tukanoPassword
      BLOB_SERVICE_HOST: blob-service
      BLOB_SERVICE_PORT: 8080
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@admin.com
  blob-service:
    build:
      context: ../TukanoBlobService
      dockerfile: Dockerfile
    container_name: blob-service-container
    volumes:
      - blob-service_data:/app/data

volumes:
  postgres_data:
  blob-service_data:
  redis_data: