apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "tukanoUser"
            - name: POSTGRES_PASSWORD
              value: "tukanoPassword"
            - name: POSTGRES_DB
              value: "tukanoDatabase"
            - name: PGDATA
              value: /var/lib/postgresql/data/db
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: docker.io/xetyz/tukano-java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOSTNAME
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOSTNAME
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "tukanoDatabase"
            - name: POSTGRES_USER
              value: "tukanoUser"
            - name: POSTGRES_PASSWORD
              value: "tukanoPassword"
          volumeMounts:
            - name: java-app-data
              mountPath: /app/data
      volumes:
        - name: java-app-data
          persistentVolumeClaim:
            claimName: java-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java-app
  type: LoadBalancer #On local environment use NodePort

---
# PersistentVolumeClaims for each service
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi